// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OGwQujEMK1_4y8VvKvRmXWG9_JJOvPc',
    appId: '1:581137144396:web:3ad16a6704d30809e0b2e9',
    messagingSenderId: '581137144396',
    projectId: 'learnandconnect-f984c',
    authDomain: 'learnandconnect-f984c.firebaseapp.com',
    storageBucket: 'learnandconnect-f984c.appspot.com',
    measurementId: 'G-E0S6YQ7J85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3WceCJ9TzY1neT_WUBXrPW1_E50_iTw',
    appId: '1:581137144396:android:b36c2e76d88b0647e0b2e9',
    messagingSenderId: '581137144396',
    projectId: 'learnandconnect-f984c',
    storageBucket: 'learnandconnect-f984c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb3BxT8NXzQ_fSfPCHhDJbzbzwvfd_9-g',
    appId: '1:581137144396:ios:a71e1da7414d96a6e0b2e9',
    messagingSenderId: '581137144396',
    projectId: 'learnandconnect-f984c',
    storageBucket: 'learnandconnect-f984c.appspot.com',
    iosBundleId: 'com.abs.learnandconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb3BxT8NXzQ_fSfPCHhDJbzbzwvfd_9-g',
    appId: '1:581137144396:ios:a71e1da7414d96a6e0b2e9',
    messagingSenderId: '581137144396',
    projectId: 'learnandconnect-f984c',
    storageBucket: 'learnandconnect-f984c.appspot.com',
    iosBundleId: 'com.abs.learnandconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OGwQujEMK1_4y8VvKvRmXWG9_JJOvPc',
    appId: '1:581137144396:web:fba3e46b0641d813e0b2e9',
    messagingSenderId: '581137144396',
    projectId: 'learnandconnect-f984c',
    authDomain: 'learnandconnect-f984c.firebaseapp.com',
    storageBucket: 'learnandconnect-f984c.appspot.com',
    measurementId: 'G-6LHQ948V9E',
  );
}
